### ISSUE TITLE
npm package doesn't match with github code

### ISSUE THREAD

**Issue by ghost** [exaptis/asciidoctor-loader#4]
Hi, I'm using asciidoctor-loader@0.1.0 in my project but I want to use the updated version with support for the new asciidoctor.js API.

I think the asciidoctor-loader@0.1.1 is not on npm. Can you publish it?

Thanks for your work!

**Comment by exaptis** [comment]
Hi, thanks for reminding me! Has been published. Have fun!

**Comment by ghost** [comment]
Thanks!
